### PR TITLE
changes made for DocumentDb

### PR DESCRIPTION
**Pull request by atomohod**
- Specification needs to be reviewed. I haven't replaced in stastic methods constructor calling for Specification.

For example: 

   public static ISpecification<T> And(ISpecification<T> specification, ISpecification<T> specification2)
        {
            return new Specification<T>(specification.And(specification2));
        }

should be replaced with something like:

public ISpecification<T> OrElse(Expression<Func<T, bool>> predicate)
        {
            return Instanciate(Predicate.OrElse(predicate));
        }

### CODE REVIEW

**Comment by jtreuting** [comment]
Thanks for the PR!  I'll try to find some time soon to pull it down and check it out.  I'm not sure I understand the comment you left about the Specification and what might need to be done there.  Can you give me a few more details around what you think is needed?  Thanks.

**Comment by eloekset** [comment]
From my build log:


Can we have this PR merged and a NuGet pre-release please?

This is the .nupkg that I've used and "deployed" to a local folder (renamed to .zip to be able to upload here).
[SharpRepository.AzureDocumentDb.0.2.0-preview.zip](https://github.com/SharpRepository/SharpRepository/files/397616/SharpRepository.AzureDocumentDb.0.2.0-preview.zip)

**Comment by jtreuting** [comment]
Sure I can pull this in.  It looks like there are merge conflicts that need to be resolved.  Did you already resolve those?  If so, can you submit a new PR that forks off of atomohod's fork.  If not, I will need to find a little bit of time later this week to take care of it.

**Comment by eloekset** [comment]
I tried to merge from develop now, but there's something related to a change where CreateSpecification is removed. I can look into it later today. It's probably the same as @atomohod has commented on.

**Pull request merged**
