### PR TITLE
Azure DocumentDb repository

### PR DESCRIPTION
**Pull request by eloekset**
I've merged and fixed the conflicts in PR #134

### CODE REVIEW

**Comment by eloekset** [comment]
#155 should be merged to fix the build errors of missing .dll files in the new AzureDocumentDb project.

**Comment by jtreuting** [comment]
Just merged #155 and it then created merge conflicts in this one :)

**Comment by eloekset** [comment]
👍 I'll update this one later today.

**Comment by eloekset** [comment]
It builds fine now. Just the same 24 tests that still fail. I've created issue #159 to investigate the failing tests. CI builds are much more useful when you can expect that they succeed. 😆

**Comment by jtreuting** [comment]
Thanks for your help!

**Comment by omarpiani** [comment]
Hey, here is the same, you are committing to develop branch, that is far back from the master branch!!

Thats why there are a lot of not working tests!

**Pull request merged**
