### PR TITLE
RedisCachingProvider added default database configuration

### PR DESCRIPTION
**Pull request by tresoldigiorgio**
For use other database number in redis. In my multi-tenant app is the only solution! :-D

### CODE REVIEW

**Comment by omarpiani** [comment]
thanks!

**Comment by tresoldigiorgio** [comment]
Can you make a new version on nuget?

**Comment by omarpiani** [comment]
released SharpRepository.Caching.Redis.2.0.2-beta1.nupkg

I have a question.. your my multi-tenant  configuration you use our repository.json file? if not, how about using it? if yes will be nice if we add a sample configuration in repository.caching.redis.json

**Comment by tresoldigiorgio** [comment]
I use default json file with this configuration:
"redisProvider": {
        "factory": "SharpRepository.Caching.Redis.RedisConfigCachingProviderFactory, SharpRepository.Caching.Redis",
        "host": "127.0.0.1",
        "port": "6379",
        "ssl": false,
        "password": "",
        "defaultDatabase": "0"
      }

I make a pull request with this file?

**Comment by tresoldigiorgio** [comment]
Yes. I have only one Redis server in cluster mode and i use a different database number for each tenant.

**Comment by omarpiani** [comment]
need to fix it. I open #216 to keep tracking

**Pull request merged**
