### PR TITLE
Little cleans and better AppVeyor compatibility

### PR DESCRIPTION
**Pull request by omarpiani**
Updated NUnit to 3.5!

Added some little cleans for a better AppVeyor test running.

### CODE REVIEW

**Comment by omarpiani** [comment]
why AppVeyor didn't restore the nuget packages?! in the other branches he did!

**Comment by omarpiani** [comment]
in my appveyor I run command "nuget restore" manually. I think I'm missing something

**Comment by eloekset** [comment]
Maybe "nuget restore" should be removed from the AppVeyor script? The BuildDependsOn stuff in this commit should make MSBuild run "nuget restore" on build: https://github.com/SharpRepository/SharpRepository/pull/155/commits/02a7561e1353fbfe7613176a84a90ec9e8c0bfc7

**Comment by omarpiani** [comment]
now I have the powers 😈, tomorrow I will check

**Comment by jtreuting** [comment]
i'm still watching ;) . (thanks!)

**Comment by eloekset** [comment]
This is the log from a build that ran three months ago. It immediately starts msbuild after cloning the repo and fetching the PR:
```
Build started
git clone -q https://github.com/SharpRepository/SharpRepository.git C:\projects\sharprepository
git fetch -q origin +refs/pull/162/merge:
git checkout -qf FETCH_HEAD
msbuild "C:\projects\sharprepository\SharpRepository.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"
Microsoft (R) Build Engine version 14.0.25420.1
Copyright (C) Microsoft Corporation. All rights reserved.

  Installing 'RavenDB.Client 2.5.2700'.
  Installing 'Microsoft.CompilerServices.AsyncTargetingPack 1.0.1'.
  Installing 'EntityFramework 6.0.1'.
  Successfully installed 'Microsoft.CompilerServices.AsyncTargetingPack 1.0.1'.
  Installing 'EnyimMemcached 2.12'.
  Successfully installed 'EnyimMemcached 2.12'.
  Successfully installed 'RavenDB.Client 2.5.2700'.
  Installing 'log4net 2.0.0'.
  Installing 'Microsoft.Data.Edm 5.6.1'.
  Successfully installed 'EntityFramework 6.0.1'.
  Successfully installed 'Microsoft.Data.Edm 5.6.1'.
  Successfully installed 'log4net 2.0.0'.
  Installing 'Microsoft.Data.OData 5.6.1'.
  Installing 'Microsoft.Data.Services.Client 5.6.1'.
  Installing 'Microsoft.WindowsAzure.ConfigurationManager 2.0.3'.
  Successfully installed 'Microsoft.Data.Services.Client 5.6.1'.
  Successfully installed 'Microsoft.WindowsAzure.ConfigurationManager 2.0.3'.
  Successfully installed 'Microsoft.Data.OData 5.6.1'.
  Installing 'mongocsharpdriver 1.8.1'.
```

**Comment by omarpiani** [comment]
All working now, AppVayor still failing because I added a failing test that evidences bug in #156

**Pull request merged**
