### PR TITLE
RepositoryFactory methods to get all existing compound key repository available

### PR DESCRIPTION
**Pull request by fiorebat**
As requested in https://github.com/SharpRepository/SharpRepository/issues/139 I did the pull request in order to fill the lack of RepositoryFactory methods to get all existing compound key repository available.

It's my first time, I hope there are no problems.

I created the overload Methods
```
RepositoryFactory.GetInstace<T, TKey, TKey2, TKey3>()
```
for triple key.

For the `ICompoundKeyRepository<T>` `GetInstance<T>` is already implemented, so I created
```
RepositoryFactory.GetCompoundKeyInstance<T>()
```

### CODE REVIEW

**Comment by jtreuting** [comment]
Awesome.  I will hopefully get a chance to review and merge this weekend.  Thanks for contributing!

**Comment by fiorebat** [comment]
jeff! don't forget me!

**Comment by jtreuting** [comment]
I totally did, I'm sorry.  I've been really busy at work.


I am going to try to get to it one night this week.  Again sorry about the delay and thanks for helping out.


________________________________

**Comment by fiorebat** [comment]
tnx, nuget package will be available?

**Comment by jtreuting** [comment]
Will be yes, not right this moment though.



________________________________

**Pull request merged**
