### PR TITLE
Remove packages from git

### PR DESCRIPTION
**Pull request by eloekset**
The packages folder shouldn't be under source control. This makes it read only and NuGet operations fail to execute.

### CODE REVIEW

**Comment by fiorebat** [comment]
appveyor is not compiling, but I think is not correctly configured for restoring packages. 

See this: https://www.appveyor.com/docs/nuget#restoring-nuget-packages-before-build

**Comment by eloekset** [comment]
Maybe we'll have to enable NuGet restore in some configuration, but it will fail anyway because of this: #154 
I can update the branch for this PR after merging the commit from #154 if it is merged into develop. If the build of this PR still fails, we'll know for sure that there's a configuration issue.

The build for #154 also fails, but that seems to be some integration tests that don't work because of missing configuration or resources not available.

**Comment by fiorebat** [comment]
only @jtreuting  can solve this

**Comment by jtreuting** [comment]
The appveyor integration tests don't run successfully, don't think they ever have because of the various data sources that would need to be installed.

**Comment by eloekset** [comment]
It seems like we have to do something to get NuGet restore on build to work. 

Should I try adding the .nuget folder with nuget.exe and nuget.targets, and add a build dependency to the MSBuild target that calls NuGet restore on BeforeBuild? If not, the issue will have to be fixed by some configuration option in appveyor, but I don't have any experience with that.

**Comment by fiorebat** [comment]
in my PR https://github.com/SharpRepository/SharpRepository/pull/145#partial-pull-merging, appveyor has worked!

**Comment by eloekset** [comment]
The build still fails, but not because of anything related to the deleted packages folder (I think). All projects compile, but 24 integration tests fail. Compared to the log of PR #145, that didn't fail, 31 new tests have been added. I guess the tests that fail now are added some time the last 4 months.

**Current test result**
Tests run: 762, Errors: 24, Failures: 0, Inconclusive: 0, Time: 1.4536662 seconds
Not run: 3, Invalid: 0, Ignored: 3, Skipped: 0

**Test results four months ago**
Tests run: 731, Errors: 0, Failures: 0, Inconclusive: 0, Time: 1.1466999 seconds
Not run: 3, Invalid: 0, Ignored: 3, Skipped: 0

What do you think @jtreuting?

**Comment by omarpiani** [comment]
Hey, here is the same, you are committing to develop branch, that is far back from the master branch!!

Thats why there are a lot of not working tests!

**Pull request merged**
