### PR TITLE
Upgraded to StructureMap 4.0

### PR DESCRIPTION
**Pull request by fiorebat**
I managed to update SharpRepository's StructureMap Ioc plugin to the brand new StructureMap 4.0 library. Code and performance is tested.

I currently testing successfully new library in my Asp.NET MVC 5 applications.

## SharpRepository.Ioc.StructureMap project
* Uses StructureMap4
* Supports new RepositoryFactory methods for ICompoundKeyRepository<T, TKey, TKey2, TKey3> and  ICompoundKeyRepository<T>  added in last commit
*  StructureMapDependencyResolver to StructureMapRepositoryDependencyResolver because that name is too common and doesn't respect BaseRepositoryDependencyResolver abstract

## SharpRepository.Tests.Integration project
* Existing test working
* New tests for the new ICompoundKeyRepository<T, TKey, TKey2, TKey3> and  ICompoundKeyRepository<T>

## SharpRepository.Benchmarks.Configuration project
* Updated succesfuly
* Test running with same performance

### CODE REVIEW

**Comment by jtreuting** [comment]
This is great.  Having this updated is really nice and I appreciate the work to make it happen.  I will try to review this in the next week or so.  If I haven't gotten it done in a week please add a comment here telling me to make it happen (as a friendly reminder of course).

**Comment by fiorebat** [comment]
8 days are passed my friend!

**Comment by fiorebat** [comment]
15 days

**Comment by jtreuting** [comment]
I am scheduling time tonight to review and approve this one and then hopefully over the weekend I will be able to look at some of the other outstanding items.


Thanks for staying on me about it, I do actually appreciate it :)



________________________________

**Pull request merged**
